### ISSUE TITLE
python2 assumed when python is in path, fails with miniconda3

### ISSUE THREAD

**Issue by LunarLanding** [jewettaij/moltemplate#30]
In moltemplate.sh:
```bash
if which python > /dev/null; then
    PYTHON_COMMAND='python2'
elif which python3 > /dev/null; then
    PYTHON_COMMAND='python3'
else
    echo "Error:  $G_PROGRAM_NAME requires python or python3" >&2
    exit 1
fi
```

This fails when conda is activated and 'python' leads to python 3+.
If I knew bash well enough I would fix this to check the version with 'python -v'

**Comment by jewettaij** [comment]
Hi Lunar
   This is distressing.  I switched the default interpreter to python2 to get around a nasty bug which only occurs using python3 (when not in debug mode).  (a "Hiesenbug").  Switching to python2 isn't really a solution either (since most people use python3).  But I will fix your problem today.  (I'll worry about this other bug later.)

**Comment by jewettaij** [comment]
I just posted an update to moltemplate that includes an attempt to fix the bug you reported.
Please try it and let me know if it resolves the issue.
-Andrew

**Comment by LunarLanding** [comment]
Hi Andrew
e619a8d3fefb199d8516dd3a76fe7172d07286cb fixes it, thanks!
