### ISSUE TITLE
906 atom types  in system.data using the OPLSAA force field

### ISSUE THREAD

**Issue by goodwilling** [jewettaij/moltemplate#35]
--------------------
moltemplate_2020-4-04/examples/all_atom/force_field_OPLSAA/
ethylene+benzene
ethylene+benzene_PACKMOL/
--------------------

For the above examples, the system.data gives 906 atom types as in the following.
I wonder why there are 906 atom types, as the actual atom types in the Atoms section  
are few.  Just the same as in oplsaa.tt ?  Thank you very much.

LAMMPS Description

     2592  atoms
     2376  bonds
     3240  angles
     3456  dihedrals
     3240  impropers

     906  atom types
     379  bond types
     1017  angle types
     800  dihedral types
     6  improper types

**Comment by jewettaij** [comment]
Hi goodwilling

Sorry, I admit this is confusing, and different from other molecule builders.  Yes, *by default*, the number of atom types which are defined equals the number of atom types defined in the "oplsaa.lt" file (n=906).  These extra atom types are harmless and do not slow down the simulations when run using CPUs.  (This might be different on GPUs.  I have not ran tests using GPUs yet.)  *However you can override this behavior.*

In each example directory, there is a file named "README_remove_irrelevant_info.sh" which explains how to remove all of the unused atom types (and bond, angle, dihedral types) from your system.data and system.in.settings files.  If you follow those instructions, you can get rid of these extra atom types.  (You just have to run the "cleanup_moltemplate.sh" script which comes with moltemplate.)

The extra atoms are not removed by default because that would erase or invalidate the "ttree_assignments.txt" file.  (That file is [incredibly helpful when trying to debug](http://moltemplate.org/troubleshooting.html) a problem with the user's LT files.)  There is probably a way to remove the unnecessary information without invalidating the contents "ttree_assignments.txt" file, but I have not spent the time to figure out how to do this yet.  (That feature would not be very useful for the coarse grained simulations that I typically run.)

When creating an LT file from scratch, it is easy to make a mistake by incorrectly typing the name of an atom or bond.  (Hopefully the moltemplate examples do not have these errors, but when you create your own example, it is easy to make a mistake.)  For users who are trying to create new molecules using moltemplate, I suggest that they should first get their example working.  Then (after they no longer need the "ttree_assignments.txt" file), they can remove the extra atom types using the "cleanup_moltemplate.sh" script.

If you think people would notice it, I could create a README.txt file containing this advice.

Thank you for the feedback.

Andrew

(After a week has gone by, if I haven't heard back from you, I will close this issue.)

**Comment by goodwilling** [comment]
Hi Andrew

Thank you very much for your detailed explanation on this point.  I have tried to run README_remove_irrelevant_info.sh and all extra information  disappear as desired. Since the extra information for atoms are useful for debug purposes,  the present scheme is reasonable and convenient. 

Thank you again for your work.

**Comment by jewettaij** [comment]
Thanks for your reply.  Glad this seems okay.  I'll close this now.
