### ISSUE TITLE
a bug to cleanmoltemplate.sh

### ISSUE THREAD

**Issue by Roy-Kid** [jewettaij/moltemplate#37]
OK, after about a whole day i finally figure out how to use TIP4P model by using `moltemplate` and oplsaa.lt
There is a bug to `cleanmoltemplate.sh`.

After I generate simulation system by moltemplate.sh, it all works well. But after using cleanmoltemplate.sh, those irrelevant information is removed, but **add set type charge** to system.in.settings. That means we use `set charge` two times: one in system.in.settings, after pair_coeff etc; another is system.in.charges. 

If i want to use TIP4P model, i should not explicitly add a dummy atom M to water.lt, but just assign the charge of M to O, thus LAMMPS would implicitly introduce  the dummy atom M to system just if your H2O has the right order. (It is a little bit imcompatible for moltemplate to LAMMPS.) Here is point. I forget that there is a system.in.charges file exists and i just rectify .settings, so .charges override my previous charge assign, so my system always blow up due to no attraction.

Anyway, I think you should do remove the function that `cleanmoltemplate.sh` copy `set charge` command to .settings. Or due to simplicity, totally remove the `system.in.charges` and write `set charge` to .settings file. Because the meaning of .settings is that settings the parameters of system.

I would pull request a example of how to build TIP4P water system and write a tutorial about how to use oplsaa force field(I think after one week study and try and  try and try i can say i understand it). But today it is too late...

**Comment by jewettaij** [comment]
I won't be able to work on moltemplate (or cleanup_moltemplate.sh) this week because I am very busy with other things right now.  But I wanted to ask a couple questions:

1) Which pair style are you using?
a) pair_style lj/cut  (and "fix rigid")
b) pair_style tip4p/long
c) pair_style lj/cut/tip4p/long
d) pair_style lj/long/tip4p/long

2) Are you using "fix rigid"?

3) Can you send me an example of an LT file containing a single molecule of TIP4P?

I would love to be able to include TIP4P in moltemplate, but I don't understand TIP4P.  If you send me a file that demonstrates how you use TIP4P in LAMMPS, it will also help me understand why "cleanup_moltemplate.sh" is not working.  (I was not able to understand why cleanup_moltemplate.sh does not work, because I do not know how many atoms are in the TIP4P molecule.)

Again, I would like to apologize now, because it will be at least a week before I can work on this problem.  But I am grateful that you reported it.

Andrew

**Comment by jewettaij** [comment]
If you would like to contribute a "tip4p.lt" file for moltemplate users to use, you can send it as a "pull-request" using github.  (This is one way that I can acknowledge you for your contribution to moltemplate.  I like to keep track of how many people contributed to it.)  But you don't have to use a "pull-request" if you don't want to.

**Comment by jewettaij** [comment]
You are correct.  After you run "cleanup_moltemplate.sh", all of the information in the "system.in.charges" file also redundantly appears in the "system.in.settings" file.  This happens because the "ltemplify.py" program does not remember the name of the file where the "set type ... charge" command originally appeared.  The "cleanup_moltemplate.sh" program writes the charge information in two files: "system.in.settings" and "system.in.charge".  I realize this is confusing, but I did not realize there is a problem.

Question: Is this a problem?

I include the same information in both files because input scripts generated by LAMMPS frequently include these two lines:

include system.in.settings
include system.in.charge

I want to make sure that the information in the 2nd file ("system.in.charge") is consistent with the information in the first file ("system.in.settings").  If the charge information only appears in one file, it is possible that the (wrong) information from the other file will will erase or override the correct file.

Alternatively, it is possible to remove the charge information from the "system.in.settings" file (so that the "set type ... charge" commands only appear in the "system.in.charge" file).  But I don't want to remove this information from "system.in.settings" unless there is a reason.  I worry that some users may forget to use "include system.in.charges".  In that case all of the atoms will have zero charge.

If the problem you are having only happens with the TIP4P water model, please send me your LT files (including "tip4p.lt", "system.lt", and any PDB files you are using).  Also tell me how you are using moltemplate.sh.  Then I will take a look.

Sorry for my slow reply.

Andrew

**Comment by jewettaij** [comment]
Dear Roy-Kid
   A quick reminder:  Please send me your tip4p example and I will have a look.  I would like to make sure tip4p works with moltemplate.

Andrew

**Comment by Roy-Kid** [comment]
[tip4p.zip](https://github.com/jewettaij/moltemplate/files/5289335/tip4p.zip)
I just have a quick test that matches the density of water to the standard value. I think this understanding is right... I hope we can have more connection and cooperation in the future!

**Comment by jewettaij** [comment]
Hi Jichen
   Thanks for the files!

   I can see that the "water.lt" files are missing some information (for example, the "pair_style lj/cut/tip4p/long" command in "implicit/oplsaa.lt" is missing some numbers we need.)  I tried to supply the missing information, but my simulations are exploding.  Can you send me the files you used for testing the water density?  Those files will probably have what I need.


1) Correction?:  According to the [documentation](https://lammps.sandia.gov/doc/pair_lj_cut_tip4p.html), we need to supply several numbers after the "pair_style lj/cut/tip4p/long" command.  So perhaps I should replace this line to the *write_once("In Init")* section at the end of the the "oplsaa.lt" file?  (line 9020)
```
pair_style lj/cut/tip4p/long
```
...with this line:
```
pair_style lj/cut/tip4p/long @atom:65 @atom:66 @bond:031_032 @angle:032_031_032 0.1250 10.0 10.0
```

2) Are you using constraints (eg. "fix shake" or "fix rigid") to keep the water molecule rigid?  *Or* are you using the force-field parameters in the OPLSAA file (which allow the water to move in a flexible way).  Either method is fine with me.  I am just curious.

3) In the "oplsaa.lt" file for the implicit version, you are using "pair_style lj/cut/tip4p/long" and "kspace_style pppm/tip4p".  I am curious what will happen if the simulation contains other molecules which are not water?  Will the "pair_style lj/cut/tip4p/long" interactions behave correctly for other atoms which are not water atoms?  (If you don't know the answer to this question, it is okay.  I think the answer is "yes".)

4) Correction?:  In the "oplsaa.lt" file, the charge and pair_coeff parameters for the TIP4P water molecules (@atom:65, @atom:66, @atom:67) [appear to be compatible with the short-range (cutoff) version of TIP4P](https://lammps.sandia.gov/doc/Howto_tip4p.html).  Since you are using the long-range version (with "kspace_style pppm/tip4p"), should we use different charges and Lennard-Jones parameters?  According to [this web page](https://lammps.sandia.gov/doc/Howto_tip4p.html), they should be:
```
O mass = 15.9994
H mass = 1.008
O charge = -1.0484
H charge = 0.5242
of OH bond = 0.9572
θ of HOH angle = 104.52
OM distance = 0.1250
LJ ε of O-O = 0.16275
LJ σ of O-O = 3.16435
LJ ε,σ of OH, HH = 0.0
```
*Don't worry about this correction for now.  We can worry about this later.*

I realize you have probably stopped using LAMMPS and moltemplate and are probably using a different program.  However if you can send me the files you used to test the TIP4P water density, that would help me.  I don't want to take up too much of your time.  (I am feeling bad that I don't have time to review your book right now.)

Thanks again.

Andrew

**Comment by Roy-Kid** [comment]
I can answer the first third of the question:
1. It's a good idea to use identifiers in write_init. Every time I change the system, I should look up the angle type in the data file and change the pair_style parameters; it is annoyed me a lot.
2. According to the understanding of mine, SHAKE is a method to constrain the vibration of the bond to stabilize the system(and reduce the computation scale). Sometimes, I forget the command, but the system still good......maybe I don't understand the algorithm very well. 
3.tip4p/long is the same as could/long. It just adds a function that can insert a dummy atom automatically. This is Alex told me on the mail list.

As for the system explode, it needs some trick. If the initial model has a very low condense or density, there is no attractive force between themselves; it is like a kind of gas. But if they are packed too close, they would not be computed kspace...so it needs to try for several times to find a proper initial configuration(even use packmol)

The last question about if I choose the correct parameter, actually I don't notice it. I find there are tip4p parameters in oplsaa.lt, so I just use it......
But the thought of how to build a tip4p water model I think is right.

I have a lot of courses in quantum mechanics this semester. Maybe on vacation, I can dive into this question.

PS: it's doesn't matter for you don't have spear time to review our book. Maybe we can write a contemplated handbook in the future!
Good luck and thanks for your kindly help!

**Comment by jewettaij** [comment]
> I can answer the first third of the question:
> 
> 1. It's a good idea to use identifiers in write_init. Every time I change the system, I should look up the angle type in the data file and change the pair_style parameters; it is annoyed me a lot.
> 2. According to the understanding of mine, SHAKE is a method to constrain the vibration of the bond to stabilize the system(and reduce the computation scale). Sometimes, I forget the command, but the system still good......maybe I don't understand the algorithm very well.

SHAKE will make existing bonds and angles rigid.  If you don't use SHAKE, the existing bonds and angles will work (but they will be flexible).  Don't worry about this detail.

>    3.tip4p/long is the same as could/long. It just adds a function that can insert a dummy atom automatically. This is Alex told me on the mail list.

Thanks!  That's very helpful and it saves me the trouble to email Axel too.

> As for the system explode, it needs some trick. If the initial model has a very low condense or density, there is no attractive force between themselves; it is like a kind of gas. But if they are packed too close, they would not be computed kspace...so it needs to try for several times to find a proper initial configuration(even use packmol)

I will play with this again someday when I have time, then.

> The last question about if I choose the correct parameter, actually I don't notice it. I find there are tip4p parameters in oplsaa.lt, so I just use it......

That's okay.

> I have a lot of courses in quantum mechanics this semester. Maybe on vacation, I can dive into this question.

I remember those days...

> PS: it's doesn't matter for you don't have spear time to review our book. Maybe we can write a contemplated handbook in the future!
> Good luck and thanks for your kindly help!

Thanks to you also.
If you don't mind, I will close this issue on github.

Andrew

**Comment by jewettaij** [comment]
Thanks again.
