### ISSUE TITLE
wrong masses in LAMMPS data file using OPLSAA force field

### ISSUE THREAD

**Issue by PatolinoSocks** [jewettaij/moltemplate#47]
Hi Andrew.

I'm trying to build a LAMMPS data file through Moltemplate. My system is formed by a carboxylic acid adduct solvated by water. For that, I'm using spce_oplsaa.lt and oplsaa.lt for water and adduct, respectively. I solved several of my issues by means your excellent answers in the LAMMPS forum. However, I have one methodological issues that I can't solve. In particular, it seems to me that Moltemplate generates wrong masses in LAMMPS data file using OPLSAA force field. All masses are being copied from oplsaa.lt to LAMMPS data file. I though that it was a problem in my LT files, but I found the same error using the system.it available example waterSPCE+methane. Do I need to do anything else with oplsaa.lt? 

Thanks in advance.
Sincerely,
Raphael

**Comment by jewettaij** [comment]
Hi Raphael
The information in the "oplsaa.lt" file is copied directly from the OPLSAA parameters which are distributed with the TINKER simulation software.  (The OPLSAA file that TINKER reads is named "oplsaa.prm" and it is located [here](https://dasher.wustl.edu/tinker/distribution/params/oplsaa.prm).)   
 So if there is a mistake in "oplsaa.lt" (the moltemplate version of OPLSAA), then there is probably a mistake in "oplsaa.prm" (the tinker version of OPLSAA) as well.
    I can't be certain, but it sounds more likely that you might have made a mistake choosing the atom types for the atoms in your molecules.  This is quite easy to do, since different atoms can have identical descriptions.  For example, see the descriptions of "@atom:96" and "@atom:97" in the [oplsaa.lt](https://github.com/jewettaij/moltemplate/blob/3db3c7277a348fb6551144b06c9967a2fed75606/moltemplate/force_fields/oplsaa.lt#L153) file are both "Alcohol -OH".  However "@atom:96" is an oxygen atom, and "@atom:97" is a hydrogen atom.

To figure out the correct "@atom" type, you need to look at both the mass and the description.

If you still can't figure it out, it *might* be helpful to look at  the corresponding "replace" statement for those atom types.  If the force field you are using contains "replace" statements, then you can find the ID numbers in those statements which are used to lookup the kinds of bonds (and angles, and dihedrals) that this atom participates in.  For example, if go to [the corresponding replace statement for "@atom:96" and "@atom:97"](https://github.com/jewettaij/moltemplate/blob/3db3c7277a348fb6551144b06c9967a2fed75606/moltemplate/force_fields/oplsaa.lt#L1983), you will see that "@atom:96" participates in the same kinds of bonds that other "b005" atoms (such as "@atom:104" and "@atom:109") participate in.  And "@atom:97" participates in the same bonds that other "b007" atoms (such as "@atom:105" and "@atom:110") participate in.  (I admit that the "b005" and "b007" numbers does not help that much in this case, because all of these other atom types unfortunately also have equally vague descriptions.)

It's actually not trivial to figure out the correct OPLSAA atom types to use in a simulation.  This is currently the major shortcoming of most molecule builder software tools, especially moltemplate. 
 Sometimes you cannot find the atom you need, and you have to pick something similar.  In rare cases, you must define a new atom type.  This often happens when you cannot find an atom type with the correct charge to neutralize your molecule.  In that case, create a new atom type which participates in the same kinds of bonds (eg. "b005"), angles ("a005"), dihedrals ("d005") and impropers ("i005") as the atom you want, but has the charge you need.

Perhaps I should update the documentation to make this more clear.

Please let me know if you resolved the issue, or if you need more help.  I'd like to resolve this issue if possible.

Andrew
P.S.  If you want to send me your files, I can hopefully take a quick look at them this weekend.

**Comment by PatolinoSocks** [comment]
Hi Andrew.

Thank you so much for your reply, detailed explanations and attention! 

I have tested your suggestions and a couple of other things else. At first I suggested that the "system.it" file available in the example waterSPCE+methane could be wrong because all masses and hence all atomic IDs from "oplsaa.lt" were copied in the "system.data" file. But this is not surely a problem. I solved the problems editing some couple of lines in the "system.lt" and "system.date" files (but maybe some atomized solution could be better). My feedback are as follows:

1) The problem isn't really related to "oplsaa.prm" (but it was interesting take a look on the source of "oplsaa.lt").

2) There was indeed a mistake choosing the hydrogen type of the H-C group (I'm working with formic acid). First, Moltemplate has warned me about a bad bond between H and C in the H-C bonding because I had choose "@atom:209" ("Carboxylic Acid -COOH") checking just the "In Charges" label. According to the "Data Masses" label in "oplsaa.lt", "@atom:209" is related to the C atom. Afterwards, I tested "@atom:212" ("Carboxylic Acid -COOH"), which has the hydrogen mass but probably it is related the hydrogen atom in the O-H bonding. Now, I choose "@atom:855" ("Tertiary Formamide H-C=O") that seems working well.

3) Finally, VMD can't read more than 9 types of elements from LAMMPS data file (this generated surely many problems!). As Moltemplate gets all masses and hence all atomic IDs from "oplsaa.lt", all types of atoms from the ID 10 are treated as the same element in VMD. Therefore, since water is solvent and it has more atoms in the final system, it's better to import "spce_oplsaa.lt" firstly in the "system.lt" file so that the H and O atoms of water are recognized respectively as IDS 1 and 2. Hence, the atomic IDs for the few atoms in formic acid from "oplsaa.lt" can be replaced manually in "Masses" and "Atom" labels in "system.data", as well as "atom types" in "LAMMPS Description" label, in order to have recognized IDs in VMD (from 3 to 9). 

I hope this helps other users.
Sincerely,
Raphael

**Comment by jewettaij** [comment]
Hi Raphael
   Thanks for getting back to me.  (I can close the issue now, but people can still find our discussion by looking through the list of closed issues.)
   Regarding 3), I agree with you.  It is very annoying that VMD assigns colors to atoms considering only the 1st character in the atom type name.  You can *(mostly)* solve this problem by following the instructions in the [README_remove_irrelevant_info.sh file](https://github.com/jewettaij/moltemplate/blob/master/examples/all_atom/force_field_OPLSAA/star_polymer/README_remove_irrelevant_info.sh)
   Basically, after you run "moltemplate.sh system.lt", just run the following command in the same directory with your "system.lt" file:
```
cleanup_moltemplate.sh
```
The documentation for this script is located [here](https://github.com/jewettaij/moltemplate/blob/master/doc/doc_cleanup_moltemplate.md#cleanup_moltemplatesh)

After you run this script, all of the extra atom types will be removed.  This does not guarantee that your system will have less than 10 atoms, but at least you wont have the entire list of 906 atom types from the original "oplsaa.prm" file.  That should help a lot.

Thanks for your feedback!
Glad it's working.

Andrew
