### ISSUE TITLE
The number of columns in your data file does not  match the LAMMPS atom_style you selected.  Use the -atomstyle <style> command line argument.

### ISSUE THREAD

**Issue by hassanuiuc** [jewettaij/moltemplate#76]
Hello! 

I got this error while running moltemplate. I saw that there was a similar issue before but the bug was fixed in v2.20.1. I'm using the current git version so I'm not sure if the bug is in this version again or there's something wrong with my files/input. I'm attaching my files incase you want to reproduce the error.

**Comment by jewettaij** [comment]
Hi hassanuiuc
   I will need your LT files to diagnose the problem, but I could find them.  Did you attach them?  Can you send them again?

**Comment by hassanuiuc** [comment]
[files.zip](https://github.com/jewettaij/moltemplate/files/8840821/files.zip)

I have attached the pdb file, the molecule lt file and system lt file. Thanks

Hassan

**Comment by jewettaij** [comment]
Hi Hassan.
The problem was caused by a missing } character in the "Data Atoms" section.  I've attached a corrected version of "acn.lt".

Meanwhile, I changed moltemplate so that it will print out a more relevant error message when this happens in the future.  (Commit 2ff9e59)

Thanks for reporting the issue!

**Comment by jewettaij** [comment]
[acn.lt.txt](https://github.com/jewettaij/moltemplate/files/8842134/acn.lt.txt)

I forgot to include the corrected file.
:P
Here it is.
