### ISSUE TITLE
[Doc] Add direct pip installation command in README.md

### ISSUE THREAD

**Issue by mjhong0708** [jewettaij/moltemplate#78]
Thanks for such a great library.

Since `pip` allows direct installation from remote git repository by running following command,
```console 
user@host:~$ pip install git+https://github.com/jewettaij/moltemplate.git
```
it will be very helpful for new users to add this in `README.md`, especially who's not familiar with python.

**Comment by jewettaij** [comment]
Hi Minjoon

Thanks for letting me know about this neat trick!  This will help users who are unfamiliar with *git*.  I think the existing instructions were really lacking, and your suggestion helped me realize this.  However I do want to encourage users to download the entire moltemplate repository because it includes a lot of documentation and examples that they will miss if they only use pip.

So I added some instructions how to use *git* to download moltemplate before using pip.  Then I also added your suggestion as well ("pip install git+https://github.com/jewettaij/moltemplate.git"), which allows users to avoid using pip.

Perhaps it makes more sense to put all the documentation and examples in a separate repository.  I tried that with [a different program I wrote](https://github.com/jewettaij/visfd), but only a few users (<10%) ever bother to download the examples (located in a [separate repository](https://github.com/jewettaij/visfd_tutorials)).

Anyway, thank you for your suggestion!  I think it will help people.
