### ISSUE TITLE
Bug in cleanup_moltemplate.sh

### ISSUE THREAD

**Issue by PhnRvTjN** [jewettaij/moltemplate#88]
This is line 226 of the script:
` if ! "${PY_SCR_DIR}/scripts/moltemplate.sh" "${BASE_NAME}.lt" \`

The correct line should have been:
` if ! "${PY_SCR_DIR}/moltemplate.sh" "${BASE_NAME}.lt" \`

**Comment by jewettaij** [comment]
HI Phani
   Thank you very much for reporting this bug.  And thank you for finding a solution!  I didn't follow up on issue #86 because from the description of the bug, I thought it was something specific to FreeBSD.  (Regrettably, I am too busy to support FreeBSD users).
 It's strange that this used to work before.  I wonder what changed.
   Your solution is a nice workaround.  *(I will have to modify your solution a little bit because the current path ("${PY_SCR_DIR}/scripts/moltemplate.sh") is still required when people [install moltemplate manually (without using pip)](https://github.com/jewettaij/moltemplate/blob/master/INSTALL.md#installation-method-2-editing-bashrc).  I'll modify the cleanup_moltemplate.sh to search fot moltemplate.sh in ${PY_SCR_DIR}/scripts/ and ${PY_SCR_DIR}/.)*

**Comment by jewettaij** [comment]
This is a great catch.

If you would like to be listed as one of the contributors to moltemplate, then feel free to [create a "pull-request" with a change to cleanup_moltemplate.sh](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

I will update moltemplate tonight.  So I suggest that you just make some trivial change (eg. add a blank line) to "cleanup_moltemplate.sh", and post a pull request.  I will approve the pull-request post a comment in your pull request explaining that you deserve the credit for fixing issue #88.)  I'll also mention this elsewhere too.

**Comment by jewettaij** [comment]
I posted your fix in the latest release ([v2.20.19](https://github.com/jewettaij/moltemplate/releases/tag/v2.20.19)).

Thank you very much again!

**Comment by PhnRvTjN** [comment]
Hello Andrew,

Thanks for the credit. I love the convenience that moltemplate offers for simulating polymers in LAMMPS and I use it regularly. Thanks for your effort.

Regards,
Phani
